name: Music Tutor Pro
favicon: null
layout_spectrum: 0.19560187659226358
typography_spectrum: 0.13245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.75
  lightness: 0.7929073453415185
  saturation: 0.7916388737503439
  rhythmicContrast: 0.6025522169657052
purpose: []
